import React, { useEffect, useState } from 'react'
import mockApi from '../../services/mockApi'
import Card from '../../components/ui/Card'
import Button from '../../components/ui/Button'

export default function ProductAdminDashboard() {
  const [products, setProducts] = useState([])

  useEffect(() => {
    mockApi.getProducts().then(setProducts)
  }, [])

  async function addProduct() {
    const newProduct = {
      id: 'p' + Date.now(),
      name: 'NewProduct' + Date.now(),
      category: 'Unknown',
      status: 'draft',
      summary: 'Autogenerated product (demo)'
    }
    await mockApi.addProduct(newProduct)
    setProducts((s) => [newProduct, ...s])
  }

  return (
    <div>
      <div className="flex items-center justify-between mb-4">
        <h1 className="text-2xl font-semibold">Product Admin</h1>
        <Button onClick={addProduct}>Add Product</Button>
      </div>

      <div className="space-y-3">
        {products.map((p) => (
          <div key={p.id} className="bg-[var(--color-surface)] p-3 rounded-[var(--radius-md)] shadow-md flex justify-between items-center">
            <div>
              <div className="font-medium">{p.name}</div>
              <div className="text-sm text-[var(--color-muted)]">{p.summary}</div>
            </div>
            <div className="flex gap-2">
              <button className="text-sm px-2 py-1 border rounded">Edit</button>
              <button className="text-sm px-2 py-1 border rounded">Queries</button>
            </div>
          </div>
        ))}
      </div>
    </div>
  )
}
